### ISSUE TITLE
Why Python?! 

### ISSUE THREAD

**Issue by AhmedIbrahim336** [rustacean-station/rustacean-station.org#168]
I wonder why a website talking about the Rust programming language is built using python :)

**Comment by jonhoo** [comment]
Ah, the Python bits are just some tools that @ericseppanen has been using to generate transcripts. The page itself is hosted with Jekyll (which is written in Ruby) through GitHub Pages, mostly because it's convenient. Ultimately though, it's really just mostly markdown :p

**Comment by AhmedIbrahim336** [comment]
Thanks for your response!
