### ISSUE TITLE
Broken timestamps in most recent podcast

### ISSUE THREAD

**Issue by VorpalBlade** [rustacean-station/rustacean-station.org#231]
https://rustacean-station.org/episode/dave-macleod/

All the timestamps are rendered into a single block without links for me.

Using Brave on Android.

**Comment by ericseppanen** [comment]
Broken for me as well, using Firefox on Ubuntu.

**Comment by ericseppanen** [comment]
The other "interviews" episodes seem to be affected as well, e.g. https://rustacean-station.org/episode/ian-ker-sey/
