### ISSUE TITLE
unable to download audio for stefan-baumgartner-rust-efficiency

### ISSUE THREAD

**Issue by ShaunSHamilton** [rustacean-station/rustacean-station.org#242]
I am unable to download the audio for https://rustacean-station.org/episode/stefan-baumgartner-rust-efficiency/

This issue is mostly to check if there is an issue with the audio file or if it is my side.

Other podcasts download and play, but in Chrome and Brave the above linked audio does not download.

<img width="1140" alt="image" src="https://github.com/rustacean-station/rustacean-station.org/assets/51722130/7ba26e5a-6b0e-4183-8570-49f01154c7cf">

<details>
  <summary>Aside Question</summary>

Is the site being debugged for anything at the moment? I see a lot of logs in the browser console when loading a page:
<img width="444" alt="image" src="https://github.com/rustacean-station/rustacean-station.org/assets/51722130/a1b9059f-0276-404d-838c-b6a6c7c9b5f5">

</details>

**Comment by ericseppanen** [comment]
It works for me under Chromium and Firefox on Linux. I'm right-clicking on the player and selecting "Save audio as".

**Comment by ShaunSHamilton** [comment]
@ericseppanen Thank you. That works for me too now, and it seems I can also play the audio as normal.
