### ISSUE TITLE
AntennaPod sync Error: "Invalid type"

### ISSUE THREAD

**Issue by d2weber** [rustacean-station/rustacean-station.org#270]
Since a coulpe of weeks (maybe scince the website is hosted on Cloudflare) AntennaPod fails to sync saying:
```
The podcast host's server sent a website, not a podcast
Technical reason: Invalid type
```
This happens with https://rustacean-station.org/podcast.rss

If I however use the github hosted file (https://rustacean-station.github.io/rustacean-station.org/podcast.rss) it works just fine.

A comparison of the HTTP Headers revealed a difference that might be the culprit: on Cloudflare its
```
$ curl -I https://rustacean-station.org/podcast.rss
content-type: application/rss+xml
```
instead of
```
content-type: application/rss+xml; charset=utf-8
```

Maybe the charset header is requried by AntennaPod (because the charset tag is set within the rss file).

For completness I also append the (somewhat uniformative) AntennaPod logs: (Actually this might be a bug in xmlpull)
```
07-07 17:31:04.019 31601  1052 W System.err: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT (�/�X����Z-1E@I...@1:94 in org.apache.commons.io.input.XmlStreamReader@379871d) 
07-07 17:31:04.032 31601  1052 W System.err: 	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
07-07 17:31:04.032 31601  1052 W System.err: 	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
07-07 17:31:04.032 31601  1052 W System.err: 	at de.danoeh.antennapod.parser.feed.util.TypeGetter.getType(SourceFile:77)
07-07 17:31:04.032 31601  1052 W System.err: 	at de.danoeh.antennapod.parser.feed.FeedHandler.parseFeed(SourceFile:22)
07-07 17:31:04.032 31601  1052 W System.err: 	at de.danoeh.antennapod.net.download.service.feed.remote.FeedParserTask.call(SourceFile:54)
07-07 17:31:04.032 31601  1052 W System.err: 	at de.danoeh.antennapod.net.download.service.feed.FeedUpdateWorker.refreshFeed(SourceFile:192)
07-07 17:31:04.032 31601  1052 W System.err: 	at de.danoeh.antennapod.net.download.service.feed.FeedUpdateWorker.refreshFeeds(SourceFile:149)
07-07 17:31:04.032 31601  1052 W System.err: 	at de.danoeh.antennapod.net.download.service.feed.FeedUpdateWorker.doWork(SourceFile:96)
07-07 17:31:04.033 31601  1052 W System.err: 	at androidx.work.Worker$1.run(SourceFile:86)
07-07 17:31:04.033 31601  1052 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-07 17:31:04.033 31601  1052 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-07 17:31:04.033 31601  1052 W System.err: 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by Skgland** [comment]
I also noticed that the latest Episode available in Youtube Music is `Rama with Glen De Cauwsemaecker` from 2024-05-19 and that `What's New in Rust 1.72 and 1.73` from 2024-06-18 isn't available. This looks related given the similar time frame since when the issue started.
Though it looks like the switch to Cloudflare d466a9f17888c211b172637ac244549fd03cd7a6 was before the former 2933d9098c84878d8d7a077b0be73df7feeb9ff5 and before the next episode b01adb43ff3d62d4186bfce8dfffa1a71b7019d5 only the 404 page was added 4ce48cf45248daa7886d61d027ad04e89b6460e3 69a0528310451eedc4f79ab4fdc91477597edd97

**Comment by Skgland** [comment]
Though I don't see a cloudflare-pages bot comment on the former episode's pr only on the next. So it looks like this matches the switch to cloudflare-pages.
