### ISSUE TITLE
Broken playback on most recent episode. 

### ISSUE THREAD

**Issue by VorpalBlade** [rustacean-station/rustacean-station.org#281]
On the most recent episode as of writing this (https://rustacean-station.org/episode/pete-levasseur/) I can't play the audio. The play button is greyed out, unlike on previous episodes that work properly.

I'm using Brave on Android. Not sure what other information could be relevant?

**Comment by jonhoo** [comment]
This _should_ since have been fixed. It was a caching problem with podtrac where it didn't recognize the new host we [temporarily used](https://github.com/rustacean-station/rustacean-station.org/pull/280#issuecomment-2452846609) for that episode.

**Comment by VorpalBlade** [comment]
Yes, it seems to work now.
