### ISSUE TITLE
Episode titles should look more clickable

### ISSUE THREAD

**Issue by ericseppanen** [rustacean-station/rustacean-station.org#36]
Each time I go to listen to an episode (from a web browser), I find myself accidentally clicking the wrong link-- I end up opening the first link in the episode description, not the episode page itself.

Even though I should know better, I've done this enough times that I think some improvement is called for.  I can think of a few different ways to handle this:

1. Make the text look a little more link-y.  E.g. the following css would help a little bit:
```
.episode h1 a {
    text-decoration: underline;
    text-decoration-color: #d6611b;
    color: inherit;
}
```
The only downside here is the page starts to look crowded with underlines everywhere, because many titles are very long, spanning multiple lines.

2. Do the same as #1, except split the really long episode titles into a short title and a longer subtitle.  Then only the title needs to look clickable.  Might take a lot of work and I don't know if retroactively changing titles could disrupt rss...?

3. Add some kind of "play button" or speaker/podcast icon to the left of the episode title+text.

4. Add a small image to the left of the episode title, something related to the episode.  I think people gravitate toward clicking images when they're not quite sure where else to click.  This could be combined with (3), e.g. a ghost of a play button over the image.

**Comment by jonhoo** [comment]
I agree with you that it seems worthwhile to do something about this. My personal preference would be to add something like an arrow to the left of each title, pointing at the title, for pretty much all the reasons you outlined above :)

**Comment by ericseppanen** [comment]
A few screenshots, showing off a few alternatives:

Add an arrow to the episode title:
![arrow](https://user-images.githubusercontent.com/36317762/81970933-233d1600-95d5-11ea-95d5-ab89321b1dca.png)

Use css "first-line" to apply an link-ish style to the first line of the title:
![firstline_linky](https://user-images.githubusercontent.com/36317762/81970946-26d09d00-95d5-11ea-9608-7d58a72ea3b5.png)

Use both the arrow and the first-line link style:
![firstline_arrow](https://user-images.githubusercontent.com/36317762/81970956-2b955100-95d5-11ea-9003-1a4dd359c785.png)

**Comment by jonhoo** [comment]
Hmm, all of those look a little odd to me. The first-line-different style in particular. I think even with the arrow, it should probably be to the left of the text like with the icons if we decide to go that direction?

**Comment by ericseppanen** [comment]
If I put the arrow in a separate div, I get this:

![arrow-separate-div](https://user-images.githubusercontent.com/36317762/81973264-bdeb2400-95d8-11ea-8d8b-6981aff53ff3.png)

I'm having trouble getting things to line up horizontally; I'm not sure why.  I'm sure it's fixable if this is getting closer to what you want.

**Comment by jonhoo** [comment]
I was actually pretty intrigued by your idea to use a sound wave icon instead of a play icon. I think that could work quite well. Plus underline-on-hover.
