### ISSUE TITLE
Wrong audio file for This Week in Rust - Issue 348

### ISSUE THREAD

**Issue by LauH1987** [rustacean-station/rustacean-station.org#68]
Listening to This Week in Rust - Issue 348 it seems that the [audio file](https://audio.rustacean-station.org/file/rustacean-station/twir-2020-07-21.mp3) is from TWIR issue 341+342

**Comment by jonhoo** [comment]
Oh, damn, that's my bad! I'll fix it shortly!

**Comment by jonhoo** [comment]
cc @nellshamrell just so you're aware

**Comment by jonhoo** [comment]
What happened was that I uploaded an old file you'd sent me by accident. Have replaced it on the CDN now, and have purged the mp3 cache.

**Comment by nellshamrell** [comment]
Ty!

**Comment by ian-h-chamberlain** [comment]
Hi, just found this issue as I typically use Spotify to listen to the podcast, and it seems to be still serving the old episode ([web link](https://open.spotify.com/episode/6f87ei0ud6YZ3HKLTdQZFn?si=HWQ7NHGySnS709U_Cn5UCg)). Is there an extra step needed to update the Spotify version?

Thanks for the podcast! Meanwhile I can just listen to https://rustacean-station.org :)

**Comment by jonhoo** [comment]
That's awkward. I [tweeted at them](https://twitter.com/jonhoo/status/1286286863523819521). See also [this Reddit thread](https://www.reddit.com/r/podcasts/comments/apgilu/updating_an_episode_on_spotify/).
