### ISSUE TITLE
Link from the transcript page to the episode page

### ISSUE THREAD

**Issue by ericseppanen** [rustacean-station/rustacean-station.org#86]
I notice that a lot of transcripts end up saying "we'll provide a link to that in the show notes," and it would be nice to have an (automatically generated?) link at the top of the transcript page "back" to the episode page.

I'm assuming here that a number of visitors may have arrived at the transcript page directly from a search engine.

I also wonder if I should adopt a transcript guideline that transcripts that mention "show notes" should hyperlink back to the episode page.

**Comment by ericseppanen** [comment]
I was dumb here-- there is already such a link.  It says "Back to Episode Page".

I suppose I can try to rescue some value from opening this issue by wondering whether that text is useful for a visitor that just arrived from a search engine... maybe it should say "Episode Page with Show Notes" or something?

**Comment by jonhoo** [comment]
I think your proposed renaming makes a lot of sense!

**Comment by ericseppanen** [comment]
Fixed by #88.
